In [1]:
import pandas as pd
import numpy as np

# 1. Load & Explore

In [2]:
df = pd.read_json('e-comm_data.json')
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct
0,ORD001,alice johnson,Laptop,Electronics,2,75000,2023-01-15,2023-01-20,Mumbai,Credit Card,Delivered,4.5,10
1,ORD002,BOB MARTIN,Phone Case,Accessories,0,299,2023/03/22,2023-03-25,delhi,UPI,delivered,3.0,5
2,ORD003,Charlie Perez,Headphones,Electronics,1,-999,2023-07-30,2023-07-28,Bangalore,Cash on Delivery,Delivered,6.0,0
3,ORD004,diana prince,Desk Chair,Furniture,1,12000,22-09-2023,None,Chennai,Debit Card,Pending,NaN,15
4,ORD005,Ethan Hunt,Notebook,stationery,5,120,2023-11-05,2023-11-07,Pune,UPI,Delivered,2.5,110
5,ORD006,None,Monitor,Electronics,1,18000,2023-06-18,2023-06-25,Hyderabad,Credit Card,Delivered,4.0,20
6,ORD007,Fiona Glenanne,Keyboard,Electronics,999,2500,2023-04-10,2023-04-13,Mumbai,Net Banking,Delivered,4.0,0
7,ORD008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,UPI,Returned,1.0,0
8,ORD008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,UPI,Returned,1.0,0
9,ORD009,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,MUMBAI,Credit Card,Delivered,5.0,25
10,ORD010,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,Mumbai,Credit Card,Delivered,5.0,25
11,ORD011,Ivan Drago,Blender,Kitchen,1,3500,2023-02-28,2023-03-05,Ahmedabad,CASH ON DELIVERY,Delivered,3.5,10
12,ORD012,Julia Roberts,Sunglasses,Fashion,-1,2200,2023-09-09,2023-09-12,Jaipur,Debit Card,Delivered,4.0,5
13,ORD013,Karl Urban,Trimmer,Grooming,1,1999,2023-14-07,2023-07-18,Surat,UPI,Delivered,3.0,0
14,ORD014,Laura Palmer,Coffee Maker,Kitchen,1,4500,2023-10-01,2023-09-28,Lucknow,Credit Card,Delivered,0.0,30
15,ORD015,Mark Twain,Novel,Books,4,350,2023-12-25,None,Bhopal,UPI,Pending,NaN,0
16,ORD016,Nancy Drew,Lamp,Furniture,2,2800,2023/05/15,2023-05-19,Nagpur,Net Banking,delivered,4.5,-10
17,ORD017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20
18,ORD017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20
19,ORD018,Priya Sharma,Saree,Fashion,3,5000,14-02-2023,2023-02-18,Varanasi,Credit Card,Delivered,5.0,15
20,ORD019,Quinn Hughes,Dumbbells,fitness,2,2200,2023-03-18,2023-03-22,Chandigarh,UPI,Delivered,99.0,10
21,ORD020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,EMI,Delivered,4.0,5
22,ORD020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,EMI,Delivered,4.0,5

In [3]:
# check dtype, shape and missing/null value
print("Shape",df.shape)
print()
print("Datatype",df.dtypes)
print()
print("Null values", df.isna().sum())

Shape (23, 13)

Datatype order_id           object
customer_name      object
product            object
category           object
quantity            int64
unit_price          int64
order_date         object
delivery_date      object
city               object
payment_method     object
status             object
rating            float64
discount_pct        int64
dtype: object

Null values order_id          0
customer_name     1
product           0
category          0
quantity          0
unit_price        0
order_date        0
delivery_date     2
city              0
payment_method    0
status            0
rating            2
discount_pct      0
dtype: int64

In [4]:
df.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct
0,ORD001,alice johnson,Laptop,Electronics,2,75000,2023-01-15,2023-01-20,Mumbai,Credit Card,Delivered,4.5,10
1,ORD002,BOB MARTIN,Phone Case,Accessories,0,299,2023/03/22,2023-03-25,delhi,UPI,delivered,3.0,5
2,ORD003,Charlie Perez,Headphones,Electronics,1,-999,2023-07-30,2023-07-28,Bangalore,Cash on Delivery,Delivered,6.0,0
3,ORD004,diana prince,Desk Chair,Furniture,1,12000,22-09-2023,None,Chennai,Debit Card,Pending,NaN,15
4,ORD005,Ethan Hunt,Notebook,stationery,5,120,2023-11-05,2023-11-07,Pune,UPI,Delivered,2.5,110

# 2 Dealing with duplicates

In [5]:
# exact duplciates
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct
7,ORD008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,UPI,Returned,1.0,0
8,ORD008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,UPI,Returned,1.0,0
17,ORD017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20
18,ORD017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20
21,ORD020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,EMI,Delivered,4.0,5
22,ORD020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,EMI,Delivered,4.0,5

In [6]:
# Drop duplicate and keep 1st occurance of each

df.drop_duplicates(keep='first', inplace=True)
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct
0,ORD001,alice johnson,Laptop,Electronics,2,75000,2023-01-15,2023-01-20,Mumbai,Credit Card,Delivered,4.5,10
1,ORD002,BOB MARTIN,Phone Case,Accessories,0,299,2023/03/22,2023-03-25,delhi,UPI,delivered,3.0,5
2,ORD003,Charlie Perez,Headphones,Electronics,1,-999,2023-07-30,2023-07-28,Bangalore,Cash on Delivery,Delivered,6.0,0
3,ORD004,diana prince,Desk Chair,Furniture,1,12000,22-09-2023,None,Chennai,Debit Card,Pending,NaN,15
4,ORD005,Ethan Hunt,Notebook,stationery,5,120,2023-11-05,2023-11-07,Pune,UPI,Delivered,2.5,110
5,ORD006,None,Monitor,Electronics,1,18000,2023-06-18,2023-06-25,Hyderabad,Credit Card,Delivered,4.0,20
6,ORD007,Fiona Glenanne,Keyboard,Electronics,999,2500,2023-04-10,2023-04-13,Mumbai,Net Banking,Delivered,4.0,0
7,ORD008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,UPI,Returned,1.0,0
9,ORD009,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,MUMBAI,Credit Card,Delivered,5.0,25
10,ORD010,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,Mumbai,Credit Card,Delivered,5.0,25
11,ORD011,Ivan Drago,Blender,Kitchen,1,3500,2023-02-28,2023-03-05,Ahmedabad,CASH ON DELIVERY,Delivered,3.5,10
12,ORD012,Julia Roberts,Sunglasses,Fashion,-1,2200,2023-09-09,2023-09-12,Jaipur,Debit Card,Delivered,4.0,5
13,ORD013,Karl Urban,Trimmer,Grooming,1,1999,2023-14-07,2023-07-18,Surat,UPI,Delivered,3.0,0
14,ORD014,Laura Palmer,Coffee Maker,Kitchen,1,4500,2023-10-01,2023-09-28,Lucknow,Credit Card,Delivered,0.0,30
15,ORD015,Mark Twain,Novel,Books,4,350,2023-12-25,None,Bhopal,UPI,Pending,NaN,0
16,ORD016,Nancy Drew,Lamp,Furniture,2,2800,2023/05/15,2023-05-19,Nagpur,Net Banking,delivered,4.5,-10
17,ORD017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20
19,ORD018,Priya Sharma,Saree,Fashion,3,5000,14-02-2023,2023-02-18,Varanasi,Credit Card,Delivered,5.0,15
20,ORD019,Quinn Hughes,Dumbbells,fitness,2,2200,2023-03-18,2023-03-22,Chandigarh,UPI,Delivered,99.0,10
21,ORD020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,EMI,Delivered,4.0,5

In [ ]:
# how to work with hannah lee

# 3. Customer Name Cleaning

In [7]:
# Fix inconsistent name casing, extra white space from all object columns

obj_col = df.select_dtypes(include=['object']).columns

# apply fix on each object col
df[obj_col] = df[obj_col].apply(lambda x: x.str.strip().str.title())

# fill Null customer with Unknown
df['customer_name'] = df['customer_name'].fillna('Unknown')
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct
0,Ord001,Alice Johnson,Laptop,Electronics,2,75000,2023-01-15,2023-01-20,Mumbai,Credit Card,Delivered,4.5,10
1,Ord002,Bob Martin,Phone Case,Accessories,0,299,2023/03/22,2023-03-25,Delhi,Upi,Delivered,3.0,5
2,Ord003,Charlie Perez,Headphones,Electronics,1,-999,2023-07-30,2023-07-28,Bangalore,Cash On Delivery,Delivered,6.0,0
3,Ord004,Diana Prince,Desk Chair,Furniture,1,12000,22-09-2023,None,Chennai,Debit Card,Pending,NaN,15
4,Ord005,Ethan Hunt,Notebook,Stationery,5,120,2023-11-05,2023-11-07,Pune,Upi,Delivered,2.5,110
5,Ord006,Unknown,Monitor,Electronics,1,18000,2023-06-18,2023-06-25,Hyderabad,Credit Card,Delivered,4.0,20
6,Ord007,Fiona Glenanne,Keyboard,Electronics,999,2500,2023-04-10,2023-04-13,Mumbai,Net Banking,Delivered,4.0,0
7,Ord008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,Upi,Returned,1.0,0
9,Ord009,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,Mumbai,Credit Card,Delivered,5.0,25
10,Ord010,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,Mumbai,Credit Card,Delivered,5.0,25
11,Ord011,Ivan Drago,Blender,Kitchen,1,3500,2023-02-28,2023-03-05,Ahmedabad,Cash On Delivery,Delivered,3.5,10
12,Ord012,Julia Roberts,Sunglasses,Fashion,-1,2200,2023-09-09,2023-09-12,Jaipur,Debit Card,Delivered,4.0,5
13,Ord013,Karl Urban,Trimmer,Grooming,1,1999,2023-14-07,2023-07-18,Surat,Upi,Delivered,3.0,0
14,Ord014,Laura Palmer,Coffee Maker,Kitchen,1,4500,2023-10-01,2023-09-28,Lucknow,Credit Card,Delivered,0.0,30
15,Ord015,Mark Twain,Novel,Books,4,350,2023-12-25,None,Bhopal,Upi,Pending,NaN,0
16,Ord016,Nancy Drew,Lamp,Furniture,2,2800,2023/05/15,2023-05-19,Nagpur,Net Banking,Delivered,4.5,-10
17,Ord017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20
19,Ord018,Priya Sharma,Saree,Fashion,3,5000,14-02-2023,2023-02-18,Varanasi,Credit Card,Delivered,5.0,15
20,Ord019,Quinn Hughes,Dumbbells,Fitness,2,2200,2023-03-18,2023-03-22,Chandigarh,Upi,Delivered,99.0,10
21,Ord020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,Emi,Delivered,4.0,5

In [8]:
# Make dates to YYYY-MM-DD

# making dates in 1 format
df['order_date'] = df['order_date'].str.replace(r'[\.,/]', '-', regex=True)

print("Datatype before:",df['order_date'].dtype)

df['order_date']

Datatype before: object

0     2023-01-15
1     2023-03-22
2     2023-07-30
3     22-09-2023
4     2023-11-05
5     2023-06-18
6     2023-04-10
7     2023-08-14
9     2023-05-29
10    2023-05-29
11    2023-02-28
12    2023-09-09
13    2023-14-07
14    2023-10-01
15    2023-12-25
16    2023-05-15
17    2023-11-11
19    14-02-2023
20    2023-03-18
21    2023-07-04
Name: order_date, dtype: object

In [12]:
# get the data and convert to date-time format and follow YYYY-MM-DD format
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', errors='coerce')
print("Data type after:",df['order_date'].dtype)
df['order_date']

#df['order_date'] = df['order_date'].dt.strftime('%Y-%m-%d') - if want to convert date col to object

Data type after: datetime64[ns]

0    2023-01-15
1    2023-03-22
2    2023-07-30
3    2023-09-22
4    2023-11-05
5    2023-06-18
6    2023-04-10
7    2023-08-14
9    2023-05-29
10   2023-05-29
11   2023-02-28
12   2023-09-09
13          NaT
14   2023-10-01
15   2023-12-25
16   2023-05-15
17   2023-11-11
19   2023-02-14
20   2023-03-18
21   2023-07-04
Name: order_date, dtype: datetime64[ns]

In [13]:
# make none/null to pending in delivery_date

df['delivery_date'] = pd.to_datetime(df['delivery_date'],  errors='coerce')
df['delivery_date']

0    2023-01-20
1    2023-03-25
2    2023-07-28
3           NaT
4    2023-11-07
5    2023-06-25
6    2023-04-13
7    2023-08-14
9    2023-06-02
10   2023-06-02
11   2023-03-05
12   2023-09-12
13   2023-07-18
14   2023-09-28
15          NaT
16   2023-05-19
17   2023-11-15
19   2023-02-18
20   2023-03-22
21   2023-07-20
Name: delivery_date, dtype: datetime64[ns]

In [14]:
df.dtypes

order_id                  object
customer_name             object
product                   object
category                  object
quantity                   int64
unit_price                 int64
order_date        datetime64[ns]
delivery_date     datetime64[ns]
city                      object
payment_method            object
status                    object
rating                   float64
discount_pct               int64
dtype: object

# 5. Logical Date Validation

In [15]:
# Find orders where delivery_date is before order_date 
df['is_date_valid'] = np.where(df['delivery_date'] < df['order_date'], "Invalid date", "Valid date")

# return rows which has Invalid date
invalid_dates = df.loc[df['is_date_valid'] == 'Invalid date']
invalid_dates

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct,is_date_valid
2,Ord003,Charlie Perez,Headphones,Electronics,1,-999,2023-07-30,2023-07-28,Bangalore,Cash On Delivery,Delivered,6.0,0,Invalid date
14,Ord014,Laura Palmer,Coffee Maker,Kitchen,1,4500,2023-10-01,2023-09-28,Lucknow,Credit Card,Delivered,0.0,30,Invalid date

# 6. Quantity Validation

In [ ]:
# Negative quantity — (ORD012)
# Zero quantity — can an order exist with 0 items? (ORD002)


# replace Negative and zero value with Nan
df.loc[df['quantity'] <= 0 , 'quantity'] = np.nan

# convert the column back to int and replace nan with NA
df['quantity'] =df['quantity'].astype('Int64')

df['quantity']

0        2
1     <NA>
2        1
3        1
4        5
5        1
6      999
7        3
9        2
10       2
11       1
12    <NA>
13       1
14       1
15       4
16       2
17       1
19       3
20       2
21       1
Name: quantity, dtype: Int64

In [18]:
# Flag Suspiciously high quantity like 999 — flag as outlier (ORD007)

suspicious_quantities = df[df['quantity'] > 100]
suspicious_quantities

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct,is_date_valid
6,Ord007,Fiona Glenanne,Keyboard,Electronics,999,2500,2023-04-10,2023-04-13,Mumbai,Net Banking,Delivered,4.0,0,Valid date

# 7 Discount validating

In [20]:
# Discount must be between 0 and 100 percent
# Find discounts over 100 or negative discounts
# Replace invalid discounts with NaN

df['discount_pct']

0      10
1       5
2       0
3      15
4     110
5      20
6       0
7       0
9      25
10     25
11     10
12      5
13      0
14     30
15      0
16    -10
17     20
19     15
20     10
21      5
Name: discount_pct, dtype: int64

In [24]:
df.loc[(df['discount_pct'] > 100) | (df['discount_pct'] < 0), 'discount_pct' ] = np.nan

# convert column back to int
df['discount_pct'] =df['discount_pct'].astype('Int64')

df['discount_pct']

0       10
1        5
2        0
3       15
4     <NA>
5       20
6        0
7        0
9       25
10      25
11      10
12       5
13       0
14      30
15       0
16    <NA>
17      20
19      15
20      10
21       5
Name: discount_pct, dtype: Int64

# 8 Price Validation

In [ ]:
# Find negative unit_price — replace with NaN
df['unit_price']

int64

0     75000
1       299
2      -999
3     12000
4       120
5     18000
6      2500
7       450
9      1800
10     1800
11     3500
12     2200
13     1999
14     4500
15      350
16     2800
17     3200
19     5000
20     2200
21    45000
Name: unit_price, dtype: int64

In [28]:
df.loc[df['unit_price'] < 0, 'unit_price'] = np.nan

df['unit_price'] =df['unit_price'].astype('Int64')

df['unit_price']

0     75000
1       299
2      <NA>
3     12000
4       120
5     18000
6      2500
7       450
9      1800
10     1800
11     3500
12     2200
13     1999
14     4500
15      350
16     2800
17     3200
19     5000
20     2200
21    45000
Name: unit_price, dtype: Int64

# 9. Rating Validation

In [29]:
df['rating']

0      4.5
1      3.0
2      6.0
3      NaN
4      2.5
5      4.0
6      4.0
7      1.0
9      5.0
10     5.0
11     3.5
12     4.0
13     3.0
14     0.0
15     NaN
16     4.5
17     4.0
19     5.0
20    99.0
21     4.0
Name: rating, dtype: float64

In [30]:
# <!-- Valid range is 1.0 to 5.0
# Find ratings of 0.0, 6.0, 99.0 — replace with NaN -->

lower_rating = 1.0
highest_rating = 5.0

# using masking
df['rating'] = df['rating'].mask((df['rating'] < lower_rating) | (df['rating'] > highest_rating))
df['rating']

0     4.5
1     3.0
2     NaN
3     NaN
4     2.5
5     4.0
6     4.0
7     1.0
9     5.0
10    5.0
11    3.5
12    4.0
13    3.0
14    NaN
15    NaN
16    4.5
17    4.0
19    5.0
20    NaN
21    4.0
Name: rating, dtype: float64

 # 10 New column for total_price

In [ ]:
# New total price column
df['total_price'] = df['quantity'] * df['unit_price'] * (1 - df['discount_pct'] / 100)
df['total_price']

# pandas handels NaN value automatically - if any of the value is NaN, the output is NaN

0      135000.0
1          <NA>
2          <NA>
3       10200.0
4          <NA>
5       14400.0
6     2497500.0
7        1350.0
9        2700.0
10       2700.0
11       3150.0
12         <NA>
13       1999.0
14       3150.0
15       1400.0
16         <NA>
17       2560.0
19      12750.0
20       3960.0
21      42750.0
Name: total_price, dtype: Float64

In [32]:
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,delivery_date,city,payment_method,status,rating,discount_pct,is_date_valid,total_price
0,Ord001,Alice Johnson,Laptop,Electronics,2,75000,2023-01-15,2023-01-20,Mumbai,Credit Card,Delivered,4.5,10,Valid date,135000.0
1,Ord002,Bob Martin,Phone Case,Accessories,<NA>,299,2023-03-22,2023-03-25,Delhi,Upi,Delivered,3.0,5,Valid date,<NA>
2,Ord003,Charlie Perez,Headphones,Electronics,1,<NA>,2023-07-30,2023-07-28,Bangalore,Cash On Delivery,Delivered,NaN,0,Invalid date,<NA>
3,Ord004,Diana Prince,Desk Chair,Furniture,1,12000,2023-09-22,NaT,Chennai,Debit Card,Pending,NaN,15,Valid date,10200.0
4,Ord005,Ethan Hunt,Notebook,Stationery,5,120,2023-11-05,2023-11-07,Pune,Upi,Delivered,2.5,<NA>,Valid date,<NA>
5,Ord006,Unknown,Monitor,Electronics,1,18000,2023-06-18,2023-06-25,Hyderabad,Credit Card,Delivered,4.0,20,Valid date,14400.0
6,Ord007,Fiona Glenanne,Keyboard,Electronics,999,2500,2023-04-10,2023-04-13,Mumbai,Net Banking,Delivered,4.0,0,Valid date,2497500.0
7,Ord008,George Mills,Water Bottle,Kitchen,3,450,2023-08-14,2023-08-14,Kolkata,Upi,Returned,1.0,0,Valid date,1350.0
9,Ord009,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,Mumbai,Credit Card,Delivered,5.0,25,Valid date,2700.0
10,Ord010,Hannah Lee,Yoga Mat,Fitness,2,1800,2023-05-29,2023-06-02,Mumbai,Credit Card,Delivered,5.0,25,Valid date,2700.0
11,Ord011,Ivan Drago,Blender,Kitchen,1,3500,2023-02-28,2023-03-05,Ahmedabad,Cash On Delivery,Delivered,3.5,10,Valid date,3150.0
12,Ord012,Julia Roberts,Sunglasses,Fashion,<NA>,2200,2023-09-09,2023-09-12,Jaipur,Debit Card,Delivered,4.0,5,Valid date,<NA>
13,Ord013,Karl Urban,Trimmer,Grooming,1,1999,NaT,2023-07-18,Surat,Upi,Delivered,3.0,0,Valid date,1999.0
14,Ord014,Laura Palmer,Coffee Maker,Kitchen,1,4500,2023-10-01,2023-09-28,Lucknow,Credit Card,Delivered,NaN,30,Invalid date,3150.0
15,Ord015,Mark Twain,Novel,Books,4,350,2023-12-25,NaT,Bhopal,Upi,Pending,NaN,0,Valid date,1400.0
16,Ord016,Nancy Drew,Lamp,Furniture,2,2800,2023-05-15,2023-05-19,Nagpur,Net Banking,Delivered,4.5,<NA>,Valid date,<NA>
17,Ord017,Oscar Wilde,Backpack,Fashion,1,3200,2023-11-11,2023-11-15,Indore,Debit Card,Delivered,4.0,20,Valid date,2560.0
19,Ord018,Priya Sharma,Saree,Fashion,3,5000,2023-02-14,2023-02-18,Varanasi,Credit Card,Delivered,5.0,15,Valid date,12750.0
20,Ord019,Quinn Hughes,Dumbbells,Fitness,2,2200,2023-03-18,2023-03-22,Chandigarh,Upi,Delivered,NaN,10,Valid date,3960.0
21,Ord020,Rachel Green,Sofa,Furniture,1,45000,2023-07-04,2023-07-20,Mumbai,Emi,Delivered,4.0,5,Valid date,42750.0

In [ ]:
# save clean json in new file
df_clean = df
df_clean.to_json("clean_data.json", orient="records", indent=4)